### ISSUE TITLE
Player stats aren't getting updated.

### ISSUE THREAD

**Issue by mcapu** [TF2Stadium/QA#15]
Lobbies might not be getting closed properly.

**Comment by vibhavp** [comment]
Pauling was closing the StopVerifier channel instead of sending an empty struct over it. Should be fixed now

**Comment by mcapu** [comment]
Fixed in https://github.com/TF2Stadium/Pauling/commit/1d7ff64f91c504dcf9b4cb6d2f5e35b51f498819 https://github.com/TF2Stadium/Pauling/commit/b6e09468e505174c2a8a5abbffccc3974137c488
