### ISSUE TITLE
If you have spaces in your username mumble freaks out

### ISSUE THREAD

**Issue by Rand404** [TF2Stadium/QA#18]
It gives you an invalid username error

**Comment by mcapu** [comment]
Also with special characters (`@`, for example).

**Comment by davidh87** [comment]
Are they being URL escaped suitably?

**Comment by mcapu** [comment]
The frontend is already escaping names, but it's also a job for Helen to do, in my opinion.

**Comment by gpittarelli** [comment]
This is now handled properly (both backend and frontend)
