### ISSUE TITLE
Lobby ended but no permanent notification on lobby page that it was closed

### ISSUE THREAD

**Issue by mwaboff** [TF2Stadium/QA#2]
http://i.imgur.com/7I6bC3W.jpg

After the lobby when i'm on this page, there  is no indication here that the lobby is closed. Perhaps some sort of permanent toast or something.

**Comment by mcapu** [comment]
Closed on https://github.com/TF2Stadium/Frontend/commit/957cee7b786f44430e6a4bc718ce0fecee4a0fa9

There's a typo on the commit :(
