### ISSUE TITLE
[Server RCON Password]  input container doesn't hide.

### ISSUE THREAD

**Issue by PipingHotCoffee** [TF2Stadium/QA#20]
Placing your cursor in the input container labeled 'Server RCON Password' without inputting anything, and then setting 'Show Password' checkbox to true creates a duplicate input container without hiding the original. Specifically when 'md-input-invalid is present. 

Also initial selection upon first page load of 'Show Password' animates RCON password 'password' input-container hidden and RCON password 'text' to visible, when it should not animate.

**Comment by gpittarelli** [comment]
The first part of this has been fixed by upgrading our UI library (angular-material) to 1.0.4 https://github.com/TF2Stadium/Frontend/pull/174

The second part is also fixed, by https://github.com/TF2Stadium/Frontend/pull/175
