### ISSUE TITLE
Mumble icon hover text always says mandatory

### ISSUE THREAD

**Issue by ghost** [TF2Stadium/QA#22]
Even if the icon is the one for optional mumble, it says mandatory.
![screenshot 2016-01-25 12 16 14](https://cloud.githubusercontent.com/assets/2838013/12549434/865218c0-c35d-11e5-8cde-0292b89cd0a6.png)

**Comment by gpittarelli** [comment]
Fixed in https://github.com/TF2Stadium/Frontend/pull/176
