### ISSUE TITLE
Suggestion: show lobby create process

### ISSUE THREAD

**Issue by Haarolean** [TF2Stadium/QA#26]
When you fill connection info and press 'ok' there are no changes and you don't know that you really pressed that button or not and you need to press it again and you'll get 'server is used by lobby already' message. So, I think, we should have a pane with message/progressbar for lobby creation process.

**Comment by gpittarelli** [comment]
Cleaning up old issues. This seems to have been fixed, though we're still working on getting more detailed progress information instead of a general "spinning circle" progress bar.
