### ISSUE TITLE
Serveme.tf integration doesn't show NA servers

### ISSUE THREAD

**Issue by jondpenton** [TF2Stadium/QA#29]
Title.

**Comment by vibhavp** [comment]
From what I could see, that was because the geoip database stored continent names in lowercase, while the backend compared them to uppercase codes. https://github.com/TF2Stadium/Helen/commit/a04bc45817cfc7b3f511004f8bf43780ca8a2a6d fixes it.

**Comment by vibhavp** [comment]
My bad, there's another issue with nginx not telling the backend the actual IP address of the user, so it defaults to the EU serveme context being used.

**Comment by HenriBeck** [comment]
Nginx acts as a proxy so you get the standard 127.0.0.1 ip for every user. Simply add a env variable HTTP_FORWARDED_COUNT and set it to 1 (if you only use 1 proxy) and this should fix the problem

**Comment by Rand404** [comment]
This has since been fixed.
