### ISSUE TITLE
Whitelist displays whitelist ID instead of which league's whitelist

### ISSUE THREAD

**Issue by mwaboff** [TF2Stadium/QA#3]
Unfortunately giving the ID number isn't very descriptive and the only reason we were going to do it is because we wanted to be able to link to custom whitelists. Since we can't have those, we should probably just say which league/season the whitelist is from.

**Comment by mcapu** [comment]
At some point we still may allow players to use custom whitelists. Also, there is a tag in the header that says which rules we are using. Maybe change the wording?

**Comment by mcapu** [comment]
It was suggested by Wiethoofd that we use whitelist names instead of ids, since they're updated automatically.

**Comment by gpittarelli** [comment]
This was implemented a while ago.
