### ISSUE TITLE
Avatar displayed incorrectly

### ISSUE THREAD

**Issue by withadancenumber** [TF2Stadium/QA#36]
happened when joining https://www.tf2stadium.com/lobby/906

minor graphical bug, used the quick slot join from main lobby page, had wrong avatar

was spooky robot instead of spooky anime girl

http://i66.tinypic.com/2hnpf77.png

using latest version of opera, no extensions, windows 10

**Comment by Rand404** [comment]
Closed since we haven't seen it occur recently.
