### ISSUE TITLE
Trying to access a closed lobby does not properly redirect to main page

### ISSUE THREAD

**Issue by mwaboff** [TF2Stadium/QA#4]
https://www.youtube.com/watch?v=Mpm9LDffMFw

From what I understand it should send us to the main page if we try to manually go to a closed lobby. It looks like it does that but what we are displayed does not contain any open lobbies. In the linked video we can see that there is actually a lobby open (visible if I manually go to the main page or click the logo) but it is not shown if I try going directly to the lobby page.

**Comment by mcapu** [comment]
This is an old bug, already fixed.
