### ISSUE TITLE
No whitelists

### ISSUE THREAD

**Issue by mwaboff** [TF2Stadium/QA#40]
https://www.tf2stadium.com/lobby/2800
https://www.tf2stadium.com/lobby/2685

Both of these were nfo servers that I think were also tragic servers. Neither of them had proper whitelists (or seemingly any whitelists at all).

**Comment by mwaboff** [comment]
I talked to the creator of the second lobby. He said he reserved it from serveme.tf itself. Apparently our site wasn't showing any open servers from serveme at the time.

**Comment by Rand404** [comment]
Should be fixed.
