### ISSUE TITLE
Unable to the "I'm ready!" after going to a steam page through stadium

### ISSUE THREAD

**Issue by frostytf2** [TF2Stadium/QA#42]
As I was waiting on a lobby, I was clicking on teammates' steam profiles as attached. It automatically opens a new tab which is nice, but when the lobby was ready that little dialogue box didn't close and seemed to overlap my "I'm ready!" button. I'm running up to date chrome, Win 10 and my computer is reasonably fast. Thanks.

![bug](https://cloud.githubusercontent.com/assets/18386201/14414001/8aa3f48e-ff58-11e5-8c84-0e3aeb352b02.PNG)

**Comment by gpittarelli** [comment]
Thanks, sorry for the late reply, just going through our github errors. I can't reproduce this on the current version, so I'm going to close. Please comment here again if you see this happen again.
