### ISSUE TITLE
Cannot link directly to a lobby or refresh on a lobby page without being redirected

### ISSUE THREAD

**Issue by mwaboff** [TF2Stadium/QA#6]
When you link directly to a lobby page or refresh the lobby page, you are redirected to the main page. This is quite frustrating if you want to link someone to a lobby you want them to join.

**Comment by mcapu** [comment]
Fixed on https://github.com/TF2Stadium/Frontend/commit/aefbad44f307b9aa3d92045513d0e2e4d0a6a521
